Repository status-im/ideas, pull requests merged in 2018-04, with the labels that each got.

#138 Create #95-les-service-model
  ideas/095-les-service-model/README.md
  ideas/095-les-service-model/links.md
  ideas/095-les-service-model/log.md
Labels: research

#144 Idea 143 Seamless Login
  README.md
  ideas/134-seamless-login.md
Labels: draft

#140 add idea: SOB Improve Onboarding
  README.md
  ideas/140-sob-improve-onboarding/README.md
Labels: SOB, in-progress

#125 Swarm Compensation
  README.md
  ideas/121-swarm-compensation/README.md
Labels: SOB, in-progress

#137 Open Bounty - Platform Usage Metrics
  ideas/122-sob-metrics.md
Labels: SOB, draft

#122 Add 88 DApp Experience draft
  ideas/88-dapp-experience.md
Labels: draft

#154 Support web3.js library
  ideas/154-support-web3.js-library.md
Labels: clojure, golang, in-progress

#133 Add extensions #101
  README.md
  ideas/101-extensions.md
Labels: draft

#139 Idea 94 - wallet compatibility
  README.md
  ideas/94-wallet-compatibility.md
Labels: in-progress

#145 Self-sovereign Identity
  ideas/145-identity.md
Labels: design, draft, smart-contract

#152 Friends Recovery (Secret Multisig)
  ideas/152-friends-recovery.md
Labels: draft

#149 [#IDEA-146] : Status GO SDK
  README.md
  ideas/146-status-go-sdk/README.md
  ideas/146-status-go-sdk/progress.md
Labels: draft, golang

#150 Gas Abstraction
  ideas/150-gas-abstraction.md
Labels: draft, research, smart-contract

#151 Username ENS subdomain registrar
  ideas/151-ens-usernames.md
Labels: clojure, design, draft, smart-contract

#153 Add Whisper visualization idea
  ideas/123-whisper-visualization.md
Labels: draft

#163 Support ERC721 tokens
  ideas/163-support-erc721.md
Labels: draft

#165 96 message tributes
  ideas/96-message-tributes.md
Labels: clojure, design, in-progress, smart-contract
